// Authored by shad0w44/Rantis/August

$modelname "props_map_editor/bee_pellet_launcher_inf.mdl"
$model "Body" "launcher_ref.smd"

$renamematerial "models/props_map_editor/combine_ball_launcher" "combine_ball_launcher_inf"
$cdmaterials "models/props_map_editor/"

$surfaceprop "metalpanel"
$illumposition -0.000 -0.000 -61.568

$sequence idle "idle" fps 30.00
$sequence explodeOut "explodeOut" fps 30.00
$sequence explodeIn "explodeIn" fps 30.00
