$ModelName "props_map_editor/bee2/clean/coop_checkpoint_sep.mdl"

$staticprop
$BodyGroup "part1"
{
	studio "coop_checkpoint_sep_1_ref.smd"
}
$BodyGroup "part2"
{
	studio "coop_checkpoint_sep_2_ref.smd"
}
$BodyGroup "part3"
{
	studio "coop_checkpoint_sep_3_ref.smd"
}
$BodyGroup "part4"
{
	studio "coop_checkpoint_sep_4_ref.smd"
}

$CDMaterials "models/props_map_editor/" "BEE2/models/props_map_editor/"

$Sequence "idle" "anim_idle"
