$staticprop

$modelname "BEE2/editor/connection_point.mdl"

$texturegroup "skinfamilies" {
{ 
	"left_lower" 
	"right_lower" 
	"left_upper" 
	"right_upper" 
}

{ 
	"antline" 
	"trans" 
	"trans" 
	"trans" 
}
{ 
	"trans" 
	"antline" 
	"trans" 
	"trans" 
}
{ 
	"antline" 
	"trans" 
	"antline" 
	"trans" 
}
{ 
	"trans" 
	"antline" 
	"trans" 
	"antline" 
}
}

$body "Body" "connection_point_ref"

$cdmaterials "BEE2/models/editor/"

$sequence idle "connection_point_ref"
