$staticprop
$modelname "BEE2/editor/tile_setter"
$body "Body" "tile_setter_ref"
$sequence idle "tile_setter_ref"

$cdmaterials "BEE2/models/editor/" "models/anim_wp/framework/"

$texturegroup "skinfamilies" {
	{ "tile_setter_black" }
	{ "tile_setter_black_4x4" }
	{ "tile_setter_white" }
	{ "tile_setter_white_4x4" }
	{ "tile_setter_nodraw" }
	{ "tile_setter_void" }
	{ "tile_setter_cutout_tile_broken" }
	{ "tile_setter_cutout_tile_partial" }
}

$hbox 0 "static_prop" -16 -16 -2 16 16 0
