// Created by Crowbar 0.19.0.0

$modelname "props_map_editor/tspen_ret_btn_sphere.mdl"

$bodygroup "Body"
{
	studio "buttonball_reference.smd"
}

$cdmaterials "models/props_map_editor/"

$surfaceprop "metalpanel"

$contents "solid"
$sequence "idle" "buttonball_anims\idle.smd" {
	fps 30
}

$sequence "explodeOut" "buttonball_anims\explodeOut.smd" {
	fps 30
}

$sequence "explodeIn" "buttonball_anims\explodeIn.smd" {
	fps 30
}

$sequence "push" "buttonball_anims\push.smd" {
	fps 30
}

