// Authored by shad0w44/Rantis/August

$modelname "props_map_editor/bee_pellet_catcher_timed.mdl"
$model "Body" "catcher_ref.smd"

$renamematerial "models/props_map_editor/ball_catcher_sheet" "ball_catcher_timed"
$cdmaterials "models/props_map_editor/"

$surfaceprop "metalpanel"
$illumposition -0.000 -0.000 -61.568

$sequence idle "idle" fps 30.00
$sequence explodeOut "explodeOut" fps 30.00
$sequence explodeIn "explodeIn" fps 30.00
