$modelname "props_map_editor/bee2/clean/sendificator/sendificator.mdl"

// $staticprop

$bodygroup "mesh"
{
	studio "hmw_sendificator_sendificator_editor.smd"
}


// $surfaceprop "metalpanel"

// $contents "solid"

// $illumposition 0 -64.834 31

$cdmaterials "models\props_map_editor\"

// $cbox 0 0 0 0 0 0

// $bbox -48.96 -48.96 -64 178.628 48.96 126

// $definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0

$sequence "idle" "hmw_sendificator_sendificator_editor.smd"
