// Made by August / Rantis / Shado0w440

// With an orange glow in the tube instead of black

$modelname "props_map_editor/bee2/p1/diversity_vent.mdl"

$model "default" "diversity_vent_ref.smd"

$cdmaterials "BEE2/models/props_map_editor/vactube" "BEE2/models/props_map_editor/"

$surfaceprop "default"

$sequence BindPose "BindPose" fps 30.00
$sequence explodeOut "explodeOut" fps 30.00
$sequence explodeIn "explodeIn" fps 30.00
