// Created by Crowbar 0.74

$modelname "props_map_editor/bee2/retro/scaff_pist_grate.mdl"

$staticprop

$bodygroup "Body"
{
	studio "under_bee2_scaff_pist_grate_ref.smd"
}


$surfaceprop "metal"

$contents "solid"

$illumposition 0 0 -32

$cdmaterials "models\props_map_editor\tspen\"

$cbox 0 0 0 0 0 0

$bbox -63.001 -63.001 -64 63.001 63.001 0

$definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" "under_bee2_scaff_pist_grate_ref.smd"