// Created by Crowbar 0.74

$modelname "props_map_editor/bee2/retro/scaff_pist_1.mdl"

$staticprop

$bodygroup "Body"
{
	studio "under_bee2_scaff_pist_1_ref.smd"
}


$surfaceprop "no_decal"

$contents "solid"

$illumposition 0 0 -130.325

$cdmaterials "BEE2\models\props_map_editor\"

$cbox 0 0 0 0 0 0

$bbox -11.5 -11.5 -260.65 11.5 11.5 0

$definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" "under_bee2_scaff_pist_1_ref.smd"