// Created by Crowbar 0.74

$modelname "props_map_editor/bee2/retro/scaff_pist.mdl"

$staticprop

$bodygroup "Body"
{
	studio "under_bee2_scaff_pist_ref.smd"
}


$surfaceprop "no_decal"

$contents "solid"

$illumposition 0 -0.001 -21.5

$cdmaterials "BEE2\models\props_map_editor\"

$cbox 0 0 0 0 0 0

$bbox -64 -64.001 -136 64.001 64 93

$definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" "under_bee2_scaff_pist_ref.smd"