// Created by Crowbar 0.74

$modelname "props_map_editor/bee2/retro/coop_spawn.mdl"

$staticprop

$bodygroup "Body"
{
	studio "under_coop_spawn_ref.smd"
}


$surfaceprop "no_decal"

$contents "solid"

$illumposition 4 -138 -48

$cdmaterials "BEE2\models\props_map_editor\"

$cbox 0 0 0 0 0 0

$bbox -104.25 -96 -96.25 352 352.25 0

$definebone "static_prop" "" 0 0 0 0 0 0 0 0 0 0 0 0


$sequence "idle" "under_coop_spawn_ref.smd"